Реализация задания спринта 5
Shtrifel/MovieQuiz-ios pull request #2
Opened 2023-01-17 05:11 UTC by Shtrifel

- Логика работы приложения разбита на несколько частей.
- Работа по генерации вопросов для квиза вынесена в отдельную сущность.
- Написан класс для ведения статистики, которая будет учитывать лучший счёт игры в квиз среди всех игр
- Статистика сохраняется в UserDefaults.

2023-01-17 12:12 UTC, tsaidov7 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +class AlertPresenter: AlertPresenterProtocol  {
final
Не забывайте проставлять данное ключевое слово для ускорения работы компилятора. Это оптимизация его работы. В таком случае он будет быстрее при вызове функции находить адрес ячейки памяти, где лежит реализации вызванной функции.
https://habr.com/ru/post/673400/

2023-01-17 12:12 UTC, tsaidov7 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: AlertPresenterDelegate?
private
Вы же инджектите делегат через конструктор, получается, переменную можно закрыть приватным модификатором

2023-01-17 12:13 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory: QuestionFactoryProtocol {
final

2023-01-17 12:13 UTC, tsaidov7 commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var delegate: QuestionFactoryDelegate?
private

2023-01-17 12:15 UTC, tsaidov7 commented on MovieQuiz.xcodeproj/project.pbxproj
> +				424E3CB3296DEC4A0024B3CB /* Movie.swift in Sources */,
Правильно не запушили файлы со шрифтами
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/212896641-3d464315-217d-45a4-8b30-9782563db87b.png">

2023-01-17 12:16 UTC, tsaidov7 commented on MovieQuiz.xcodeproj/project.pbxproj
> +				424E3CB3296DEC4A0024B3CB /* Movie.swift in Sources */,
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/212896785-d228b1cc-8830-414e-9932-933f3af6391b.png">

2023-01-17 12:17 UTC, tsaidov7 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let questionsAmount: Int = 3
Вопросов же 10 должно быть

2023-01-17 13:38 UTC, Shtrifel commented on MovieQuiz/Services/QuestionFactory.swift
> +class QuestionFactory: QuestionFactoryProtocol {
Исправил

2023-01-17 13:38 UTC, Shtrifel commented on MovieQuiz/Services/QuestionFactory.swift
> +    weak var delegate: QuestionFactoryDelegate?
Исправил

2023-01-17 13:39 UTC, Shtrifel commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private let questionsAmount: Int = 3
Исправил

2023-01-17 13:41 UTC, Shtrifel commented on MovieQuiz.xcodeproj/project.pbxproj
> +				424E3CB3296DEC4A0024B3CB /* Movie.swift in Sources */,
Повторно сделал пуш и пулл реквест с учетом Sprint 04 - шрифты добавлялись в этом спринте

2023-01-17 13:41 UTC, Shtrifel commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: AlertPresenterDelegate?
Исправил

2023-01-17 13:41 UTC, Shtrifel commented on MovieQuiz/Presentation/AlertPresenter.swift
> +class AlertPresenter: AlertPresenterProtocol  {
Исправил

2023-01-18 17:24 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
> +				424E3CB3296DEC4A0024B3CB /* Movie.swift in Sources */,
@Shtrifel все еще не исправлено, ссылка на шрифты относительная: проект на твоем компьютере их находит, а на нашем нет. 

Чтобы исправить: удали файлы из проекта и добавь еще раз с копированием в директорию. Проверь чтобы при добавлении такая галка была, плюс чтобы был выставлен таргет проекта. Ну и финальную проверку: после проект должен запуститься со шрифтами. 

<img width="1512" alt="Снимок экрана 2023-01-18 в 19 21 11" src="https://user-images.githubusercontent.com/20269264/213251158-aa94cb07-efdb-46c3-b609-2fab1f983d34.png">

<img width="765" alt="Снимок экрана 2023-01-18 в 19 20 55" src="https://user-images.githubusercontent.com/20269264/213251149-0cde1aeb-2c63-4cf7-8937-4fb0d3472049.png">

2023-01-18 17:26 UTC, ABashkirova commented
@Shtrifel обрати внимание на результаты первой игры:
- почему-то рекорд нулевой, ожидаю увидеть тоже значение, что и в первой игре
- сообщение не совсем по макету построено: у даты скобок не хватает
- еще с прошлого спринта заметила: у slpash screen картинка не заполняет необходимое пространство, можно увидеть белые полосы, content mode надо исправить 

<img width="512" alt="Снимок экрана 2023-01-18 в 19 25 03" src="https://user-images.githubusercontent.com/20269264/213251612-15b1b367-1579-4fbe-bd0a-13363b8d68ee.png">
<img width="512" alt="Снимок экрана 2023-01-18 в 19 24 18" src="https://user-images.githubusercontent.com/20269264/213251936-f892e225-42f0-46c2-a3fb-5ac4b35ba250.png">

2023-01-18 17:28 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                switchButton()
давай еще форматирование поправим: выдели код и зажми control+i

2023-01-19 06:17 UTC, Shtrifel commented
- нулевой рекорд в 1-й игре - исправил
- сообщение не по макету - исправил
- slpash screen - исправил
- форматирование - исправил

2023-01-19 06:38 UTC, ABashkirova commented
> - нулевой рекорд в 1-й игре - исправил
> 
> - сообщение не по макету - исправил
> 
> - slpash screen - исправил
> 
> - форматирование - исправил

Шрифты удалось добавить?

2023-01-20 06:30 UTC, Shtrifel commented
Шрифты - добавил, да, спасибо

2023-01-24 13:14 UTC, Shtrifel commented
@ABashkirova добавил комментарий по ошибке в следующем пулРеквесте https://github.com/Shtrifel/MovieQuiz-ios/pull/6 (его же отправлял на ревью) - ошибка с нулевым рекордом не воспроизводится.

2023-01-24 19:40 UTC, ABashkirova requested changes
Ошибка все еще повторяется. Ниже предложение, как исправить

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +        }
Мне в первый раз этот кусочек показался странным, потому что по идее в первую же игру ты должен попасть в условие if newGame > bestGame и перезаписать игру.

Но у тебя этого не происходило, полагаю, поэтому пришлось вставить этот костылек.

Предлагаю его удалить, и разобраться в причине :)

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Когда я тестила в первый раз, я обычно еще проверяю блокировку кнопок: то есть очень быстро жму все подряд.

Что обычно приводит к дополнительным вызовам этого кода. Мне не очень очевидно, все ли ок в момент когда ты делаешь toggle буля, поэтому предлагаю написать аккуратный стейт:
`setEnabledButtons(isEnabled: Bool)` – внутри явно проставить значение аргумента свойству isEnabled у кнопок.

Поправить придется 
- сигнатуру метода:
- в этой функции сделать один вызов, разблокировать кнопки для случая else, а в случае выигрыша, разблокировать надо будет в комплишне алерта после self.questionFactory?.requestNextQuestion().
- и один раз заблокировать соответсвенно в методе showAnswerResult

Это даст нам хоть немного гарантий :)

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
```suggestion
    private func setEnabledButtons(isEnabled: Bool)  {
        noButton.isEnabled = isEnabled
        yesButton.isEnabled = isEnabled
    }
```

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Models/GameRecord.swift
> +    }
А вот здесь у нас как раз кроется баг, причем очень хитрый. 

Итак, чтобы повторить, давай запустим приложение и попробуем много раз кликать, пока не увидим алерт. 
У меня здесь по прежнему 0/0. gameCount при этом уже инкрементирован, поэтому если запись не произойдет то эта функция будет работать так:

lhs correct 0 / total 0 -> nan 
сравнение с lhs correct 4 / total 10  - 0.4
nan <= 0.5 даст фолс. 
(Внизу пример в отладчике) 

Я вообще очень удивлена, что мы здесь не упали с ошибкой и отлаживать такой баг действительно бывает сложно! 
Итак, в программировании обычно работают правила школьной программы – на ноль делить нельзя (дискретные вычисления, никаких бесконечностей!). 
Поэтому логичное предложение, что лучше сравнивать отношения, здесь не совсем корректны, потому что тебе придется написать проверки, что total'ы не равны нулю. А это по бизнес логике не совсем отражает действительность, поэтому предлагаю этим даже не занимать.

Эту функцию корректнее написать в лоб:`lhs.correct < rhs.correct` (оставляю тебе подумать про знак, потому что если игры с одинаковым счетом, запись должна быть у самой свежей). 

<img width="1222" alt="Снимок экрана 2023-01-24 в 20 59 04" src="https://user-images.githubusercontent.com/20269264/214387692-1d26fd8b-3bea-4787-bb37-8999a4e3c61c.png">

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Models/Movie.swift
> +}
Лишний код, давай удалять

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    init(delegate: AlertPresenterDelegate) {
давай договоримся, между объявлением новых функций оставлять одну пустую строку

2023-01-24 19:40 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    }
а здесь поправим форматирование – выделить код и зажать `control+i`

2023-01-25 04:09 UTC, Shtrifel commented on MovieQuiz/Models/GameRecord.swift
> +    }
Как раз, чтобы сохранить тут сравнение процента, а не количества правильных ответов, добавлял в statisticServices обработку первой игры 
 if gamesCount == 0 {
      bestGame = newGame
        }
- при запуске функции store, при любом раскладе, total = 0 в делителе тут возникать не должен - смоделировать ошибку не получилось - видимо какое-то хитрое сочетание в нажатии кнопок нужно  сделать.
Ок, ставлю сравнение только количества правильных ответов

2023-01-25 04:12 UTC, Shtrifel commented on MovieQuiz/Services/StatisticService.swift
> +        }
Да, после первого замечания добавил обработку первой игры, при работе функции - нуля в делителе при сравнении возникать не должно было, поэтому и странно, что ошибка у тебя оставалась.

2023-01-25 04:13 UTC, Shtrifel commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Добавил, это, видимо, и было причиной ошибки

2023-01-25 04:13 UTC, Shtrifel commented on MovieQuiz/Models/Movie.swift
> +}
ок

2023-01-25 04:13 UTC, Shtrifel commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    init(delegate: AlertPresenterDelegate) {
ок

2023-01-25 04:13 UTC, Shtrifel commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    }
ок

2023-01-25 04:17 UTC, Shtrifel commented
@ABashkirova изменения файлов в следующем пулРеквесте https://github.com/Shtrifel/MovieQuiz-ios/pull/6 (его же отправлял на ревью)

2023-02-07 11:14 UTC, merged