Sprint#06
Shtrifel/MovieQuiz-ios pull request #7
Opened 2023-02-07 11:41 UTC by Shtrifel

Реализация задания спринта 06 (Работа с сетью)

2023-02-07 23:12 UTC, mmbabaev requested changes

2023-02-07 23:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
private

2023-02-07 23:12 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//        questionFactory?.requestNextQuestion()
удалить

2023-02-07 23:12 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +    private var delegate: QuestionFactoryDelegate?
здесь убрали weak модификатор, появился reference cycle

2023-02-07 23:12 UTC, mmbabaev commented on MovieQuiz/Services/MoviesLoader.swift
> +        // Если мы не смогли преобразовать строку в URL, то приложение упадёт с ошибкой
предлагаю убрать учебные комменты

2023-02-08 05:45 UTC, Shtrifel commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//        questionFactory?.requestNextQuestion()
удалено

2023-02-08 05:45 UTC, Shtrifel commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var activityIndicator: UIActivityIndicatorView!
Добавил

2023-02-08 05:46 UTC, Shtrifel commented on MovieQuiz/Services/QuestionFactory.swift
> +    private var delegate: QuestionFactoryDelegate?
Вернул weak

2023-02-08 05:47 UTC, Shtrifel commented on MovieQuiz/Services/MoviesLoader.swift
> +        // Если мы не смогли преобразовать строку в URL, то приложение упадёт с ошибкой
Тут убрал, остальные пока оставлю (если не критично) - пока что удобнее находить нужные места с помощью комментов

2023-02-08 05:48 UTC, Shtrifel commented on MovieQuiz/Services/MoviesLoader.swift
> +        // Если мы не смогли преобразовать строку в URL, то приложение упадёт с ошибкой
По поводу пункта "Для размышления" - спасибо,сделаю в рамках следующего задания (спринт 7)

2023-02-12 20:37 UTC, merged